### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by Rastuasi** [hotbso/o4xpsm#1]
When running python3 install script, it bombs because it tries creating a link to "1200_forests", but the Linux folder for that is "1200 forests" no _. I could bypass this by manually creating the link to "1200 forests" and then naming the symlink to 1200_forests that the script wanted.

**Comment by hotbso** [comment]
Strange. The scripts does the equivalent of creating a symlink
`ln -s "../../Resources/default scenery/1200 forests" 1200_forests`
and the same code works on macOS that has a linux-like OS under the hood.
So pls delete the "1200_forests" symlink, run the script again and send a screenshot with the exact error message.

**Comment by Rastuasi** [comment]
![Screenshot from 2023-08-05 15-39-30](https://github.com/hotbso/o4xpsm/assets/17036015/a3e945fb-bcb0-4946-9d29-285bee890d5d)

![image](https://github.com/hotbso/o4xpsm/assets/17036015/cc673ea3-b427-4cef-933d-315813f93d17)

Looking at the python, it is getting the wrong path.

**What python was grabbing (took out user name/middle files that are not necessary):** /run/media/.../X-Plane 12/Resources/default scenery/1200 forests

**What it should have picked up:** /home/.../X-Plane 12/Resources/default scenery/1200 forests

So that leads to a bad link:
![image](https://github.com/hotbso/o4xpsm/assets/17036015/41564442-2a45-4663-ab66-2521292ecbe8)

This may be caused by it not accounting for the fact that "Custom Scenery" itself is already a symbolic link back to an external drive and so it's getting a bad reference as the main sim is not on the same drive, so resources/default scenery is thusly on a different drive.

**Comment by hotbso** [comment]
I'm afraid in this configuration there is no way to determine the location of X Plane's root folder.

**Comment by Rastuasi** [comment]
Yeah I was digging through potential routes and testing, I've gotten it to report back the proper parental route, so getting it outside the external drive.. but it still gets hung up on that absolute location.

I know it is common practice to put the custom scenery on a secondary drive and link it into the main drive's install, especially for those who build their own ortho. 

Probably an easier way would be to either run the install from within the main folder of XP, where it tracks down the custom scenery from there or simply take user input in, have us users in the command line, give you the full location. However, from an automation point of view, having the install run from within the home of XP and then it just knows to navigate and put the files in customscenery would be easiest?

**Comment by hotbso** [comment]
The script now detects a non-standard install of XP and provides a "-root" option
